import { Sidebar } from '@/components/Sidebar'
import './globals.css'
import { Figtree } from 'next/font/google'
import { UserProvider } from '@/providers/UserProvider'
import { SupabaseProvider } from '@/providers/SupabaseProvider'
import { ModalProvider } from '@/providers/ModalProvider'
import { ToasterProvider } from '@/providers/ToasterProvider'
import { getSongsByUID } from '@/actions/getSongsByUID'


const figtree = Figtree({ subsets: ['latin'] })

export const metadata = {
  title: 'Listnr',
  description: 'Generated by create next app',
}

export const revalidate = 0; 

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {

  const userSongs = await getSongsByUID();

  return (
    <html lang="en">
      <body className={figtree.className}>
        <ToasterProvider />
        <SupabaseProvider>
          <UserProvider>
            <ModalProvider />
            <Sidebar songs={userSongs}>
              {children}
            </Sidebar>
          </UserProvider>
        </SupabaseProvider>
      </body>
    </html>
  )
}

